# Generated by Django 4.1.5 on 2023-01-22 13:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("worldatlas", "0002_room"),
    ]

    operations = [
        migrations.AddField(
            model_name="room",
            name="first_turn",
            field=models.IntegerField(blank=True, default=0),
        ),
    ]
