# Generated by Django 4.1.5 on 2023-01-22 13:39

from django.db import migrations, models
import worldatlas.models


class Migration(migrations.Migration):

    dependencies = [
        ("worldatlas", "0003_room_first_turn"),
    ]

    operations = [
        migrations.AlterField(
            model_name="room",
            name="first_turn",
            field=models.IntegerField(
                blank=True, default=worldatlas.models.Room.generate_random_turn
            ),
        ),
    ]
